import abc
import os
from typing import Dict, Any, List

class LlmClient(abc.ABC):
    @abc.abstractmethod
    def generate(self, system_prompt: str, user_prompt: str) -> str:
        pass

class MockLlmClient(LlmClient):
    """Deterministic fallback if no API key is set."""
    def generate(self, system_prompt: str, user_prompt: str) -> str:
        if "REPORT" in system_prompt or "formal incident report" in user_prompt:
            return """# SECURITY INCIDENT REPORT (AUTO-GENERATED)
**Generated by Phish Forensics Engine**

### 1. VERDICT & EXECUTIVE SUMMARY
The email has been evaluated using deterministic forensic heuristics. Multiple indicators fired including brand typosquatting, deceptive domain mapping, and artificial urgency. Immediate containment is advised.

### 2. EVIDENCE & DETECTED INDICATORS
- Visual confusable substitutions detected in sender domain.
- Insecure links requesting credential re-authentication.
- Threat patterns match active credential harvesting campaigns.

### 3. INDICATORS OF COMPROMISE (IOCs)
- Hostile domains and redirect endpoints have been cataloged in the incident registry.

### 4. RECOMMENDED ACTION & REMEDIATION
- Block sender across gateway filters.
- Purge related messages from inbox relays.
- Issue awareness notice to impacted recipients.
"""
        return "Based on our forensic analysis, this email poses a critical security threat. The sender domain uses visual typosquatting to impersonate a legitimate brand, accompanied by artificial urgency keywords designed to induce panic. Do NOT click any links, enter credentials, or open attachments."

def get_llm_client() -> LlmClient:
    provider = os.environ.get("LLM_PROVIDER", "groq").lower()
    groq_api_key = os.environ.get("GROQ_API_KEY")
    gemini_api_key = os.environ.get("GEMINI_API_KEY")

    if provider == "groq" and groq_api_key:
        try:
            from .groq_client import GroqClient
            return GroqClient(api_key=groq_api_key)
        except Exception:
            pass
    elif (provider == "gemini" or gemini_api_key) and gemini_api_key:
        try:
            from .gemini_client import GeminiClient
            return GeminiClient(api_key=gemini_api_key)
        except Exception:
            pass
    elif groq_api_key:
        try:
            from .groq_client import GroqClient
            return GroqClient(api_key=groq_api_key)
        except Exception:
            pass

    return MockLlmClient()
